project:
  type: book

book:
  title: "Algorithms & Data Structures with C"
  author: "Igor Dimitrov"
  date: "5/17/2024"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



